Investigate tool tip z index on code groups
mintlify/components pull request #44
Opened 2023-01-27 14:44 UTC by NicoZweifel

Investigates https://github.com/mintlify/components/issues/42

I added a Margin to the CodeGroup like with the CodeBlock since z-index won't work when the tooltip is out of bounds, for example in storybook it will not work

- with z-index (no change in storybook):
![image](https://user-images.githubusercontent.com/34443492/215113497-fde9b643-78d9-45d6-9af0-b969bcf529d8.png)
- normal CodeBlock
![image](https://user-images.githubusercontent.com/34443492/215113921-4a802c8e-7883-4c73-9a86-1a0e9b019dd8.png)
![image](https://user-images.githubusercontent.com/34443492/215113959-a81db6af-736f-4f77-b455-1062644c3852.png)

Adding the margin makes the Code Group behave the same way as the CodeBlock, but I am not sure if that is desired or will break the layout in some places without adjustments in the client.

2023-01-27 20:55 UTC, tobias-mintlify requested changes
We can't add margin to the CodeBlock because it's meant to stick to the top of the page when you scroll down. The z-index not working out of bounds is a fine trade-off. We never have the CodeBlock in those situations; the goal is just to show it above the nav bar.

That being said, we should add margin to the _story_ so we can see the tooltip without overflow.

-- Tangent below --

CodeBlock is not supposed to have margin either haha. The margin on components are a hacky fix to get margins working in the MDX content. Tailwind Typography handled the margins for the text but we need a more robust way of handling margins for the custom components than hard-coding into each one.

2023-01-27 21:56 UTC, NicoZweifel commented
Yeah I think it is better to not have the margin at all as well, going to change this to z-index soon and add a decorator to the codeblock stories.

2023-01-28 18:13 UTC, NicoZweifel commented
Doesn't seem to work with z-index in the client unfortunately, I'll check some more when I have time 👍

2023-01-28 18:59 UTC, NicoZweifel commented
Seems to be because the client uses `z-50` for the navbar, I changed it to 50 here, maybe we can use 40 in the client for the navbar to solve this.

2023-01-28 19:09 UTC, NicoZweifel commented
It might also be a good idea to separate the responsibility of the z-index classes.

- z-50: reserve for overlays
- z-40: popups, tooltips etc.
- z-30: navbars, sidebars etc.

Could of course always seperate them more, for example depending on if the sidebars should be behind the navbars.

2023-01-29 05:51 UTC, tobias-mintlify approved these changes
I'll make a PR standardizing the z-index on `client`

2023-01-29 05:51 UTC, merged