add background to cover code text
mintlify/components pull request #88
Opened 2023-06-26 19:32 UTC by bryankang

<img width="284" alt="image" src="https://github.com/mintlify/components/assets/20213114/e3d87126-220e-45bb-9363-4f067ebab3e4">

<img width="94" alt="image" src="https://github.com/mintlify/components/assets/20213114/1492b041-7c22-436a-a258-e6c4eacc0a8c">

I believe the user was explicitly setting the content to `nowrap` which is probably not optimized for this component. There's still the side effect of partially covering the text, but I didn't want to change too much and possibly break things visually since I don't have enough context/time.

2023-06-26 19:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mintlify/components?pullRequest=88) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mintlify/components?pullRequest=88) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mintlify/components?pullRequest=88) it.</sub>

2023-06-26 19:51 UTC, katemintlify requested changes
Can we set the text width so that it ends before the icon? Then it doesn't look like the icon is just interrupting the text. If they use nowrap they can scroll to the overflow

2023-06-27 14:31 UTC, bryankang commented
that was my first attempt, but i saw that there are two variations of this component, and it will affect the other. but i'll see what i can do - just didn't want to spend too much time on this because of the main project

2023-06-27 14:46 UTC, bryankang commented
yeah so i think i got it. i need to double check with the other filename variant, but it looks like this.

<img width="540" alt="image" src="https://github.com/mintlify/components/assets/20213114/226cd504-1eb9-46ba-aef9-0d8fd54f0207">

is this good? if not, i can come up with a fitting scroll bar design and implement it. again, i'm just not sure how far we want to take these things given that i only have 2 days left

2023-07-10 16:15 UTC, closed without merging